### ISSUE TITLE
[Tracker] Chapters for OMG/ISO

### ISSUE THREAD

**Issue by bact** [spdx/spdx-spec#1009]
- [x] Cover pages
  - [x] one for LF 
  - [x] one for OMG
- [x] Copyrights and licensing page -- #1010
  - [x] #1036
- [x] Table of contents
- [x] Preface (add for OMG version of spec) -- #1011
- [x] Forward (add once ISO JTC-1 approves and we are sending final spec to ISO) -- #1001
- [x] Introduction -- #1007
- [x] 1 Scope -- #1005
- [x] 2 References -- #1006
  - These PRs made changes to link labels/link URLs, or made changes to names. Just a reminder to keep links in the References chapter and links in the model file in sync.
    - [x] https://github.com/spdx/spdx-3-model/pull/806
    - [x] https://github.com/spdx/spdx-3-model/pull/808
    - [x] https://github.com/spdx/spdx-3-model/pull/810
    - [x] https://github.com/spdx/spdx-3-model/pull/811
    - [x] https://github.com/spdx/spdx-3-model/pull/812
    - [x] https://github.com/spdx/spdx-3-model/pull/813
    - [x] https://github.com/spdx/spdx-3-model/pull/817
    - [x] https://github.com/spdx/spdx-3-model/pull/819
    - [x] https://github.com/spdx/spdx-3-model/pull/820
    - [x] https://github.com/spdx/spdx-3-model/pull/828
    - [x] https://github.com/spdx/spdx-3-model/pull/826
    - [x] https://github.com/spdx/spdx-3-model/issues/816
- [x] 3 Terms and definitions -- #1004
  - [x] Now in https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/terms-and-definitions.md
- [x] 4 Symbols -- #1003
- [x] 5 Conformance -- #1002
  - [x] #987 -- Now in 3.1
- [x] 6 Models and Serializations
  - [x] #998
  - [x] #1032
  - Update info about serialization and NamespaceMap:
    - [x] #1016
    - [x] https://github.com/spdx/spdx-3-model/pull/821
  - [x] https://github.com/spdx/spdx-3-model/pull/802
- [x] 7 Core Profile
- [x] 8 Software Profile
- [x] 9 Security Profile
- [x] 10 Licensing Profile
- [x] 11 Dataset Profile
- [x] 12 AI Profile
- [x] 13 Build Profile
- [x] 14 Lite Profile
  - [x] https://github.com/spdx/spdx-3-model/pull/843 
- [x] 15 Extension Profile
- [x] Annex A: Diffs from Previous Editions
  - [x] #999 
  - [x] #1035
  - Relationship type translation table is not complete yet
    - [x] #1019
- [x] Annex B: RDF Object Model and Identifier Syntax
  - [x] #936 
  - [x] #1058
- [x] Annex C: SPDX License Expressions
- [x] Annex D: SPDX license list matching guidelines
  - [x] https://github.com/spdx/spdx-3-model/issues/747
  - [x] https://github.com/spdx/spdx-spec/pull/1026
- [x] Annex E:  Package URL specification
- [x] Annex F: History, Motivation and Rational -- #1053
- [x] Annex G: Community Specification License 1.0
- [x] Annex H: Creative Commons Attribution License 3.0 Unported
- [x] Annex I: SPDX Lite

----

### Notes
- Heading consistency: Some chapter/annex headings capitalize the first word and lowercase the rest, while the other capitalize (almost) every words. Should stick to one style. (Exceptions can be made for proper nouns/names)
  - "SPDX license list matching guidelines" vs "History, Motivation and Rational"
  - See comments here: https://github.com/spdx/spdx-spec/pull/992#issuecomment-2269063388
- A question about ref consistency -- #1012
  - [ ] https://github.com/spdx/spdx-spec/issues/1060
- Do we need to also have a subsection on Stylistic/Typographical Conventions ? -- #1000
- Generated files
  - <s>https://github.com/spdx/spdx-3-model/issues/788</s> -- Moved to 3.1
  - [ ] #979
- Model
  - [x] https://github.com/spdx/spdx-3-model/pull/800
  - [x] Core/Element -- https://github.com/spdx/spdx-3-model/issues/805 -- Now in 3.1
  - [x] Core/specVersion -- https://github.com/spdx/spdx-3-model/issues/733
  - [x] Core/spdxId -- https://github.com/spdx/using/issues/7 -- Now in using
  - [x] https://github.com/spdx/spdx-3-model/pull/853
- Typos
  - [x] https://github.com/spdx/spdx-3-model/pull/817
  - [x] https://github.com/spdx/spdx-3-model/pull/824
- Pending TODOs
  - https://github.com/spdx/spdx-spec/issues/944

**Comment by bact** [comment]
@goneall @zvr From the TOC above, the changes to the model are in the remaining 3 open PRs at "2. References". Thank you.

**Comment by goneall** [comment]
Completed
