### ISSUE TITLE
Translation Decisions, documentation and TODOs

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#1169]
On the 17 Dec 2024 tech call, an issue was raised that we should document translations in the "repository".

I've searched through all open and closed issues and pull requests for "translation" as well as the minutes repo for Asia and tech.

This issue summarizes outstanding decisions, undocumented decisions, documented decisions and process, and outstanding actions to support translating the spec.

Below are some detailed decisions that still seem unresolved:

- [ ] Agree on whether version tags in the spec and model repos should be considered immutable.  See issue discussed in #1155  On one of the tech call, the consensus of the attendees was immutable, but we didn't have Alexios on the call.
- [ ] Agree on the name of the tags that would be used once the translation for a particular language has been merged into the support branch.  Proposals are to append the language code (e.g. 3.0.1-ja-ru-es), or just increment a suffix to the patch version (e.g. 3.0.1-l1, 3.0.1-l2, 3.0.1-l3).  See discussion in #1155 

Below are decisions we've made that can be documented:

- [ ] Translations will be made on a separate branch or in a separate repository and when ready, a pull request will be made against the support branch for the version the translation is made for - see discussion in #1155 Note that translations being targeted to the support directory are already documented in the README branches section.
- [ ] MKDocs will generate the languages (see [2024-05-21 minutes](https://github.com/spdx/meetings/blob/main/tech/2024/2024-05-21.md))
- [ ] We will implement a language dropdown for the website from MKDocs (see [2024-05-21 minutes](https://github.com/spdx/meetings/blob/main/tech/2024/2024-05-21.md))
- [ ] We will structure the spec repo documentation as separate directories for different languages under the docs directory - see [2024-06-06-translation minutes](https://github.com/spdx/meetings/blob/main/tech/2024/2024-06-06-translation.md)

Below are additional translation actions that need to be completed:

- [ ] Complete and merge PR #1164 to update the CI for the new branch structure
- [ ] Update MKDocs and directory structure to separate the docs into separate language directories
- [ ] Update CI and MKDocs to publish MKDocs with the language dropdown

Below are items I believe are already documented:

- [Translation format for the SPDX model repo](https://github.com/spdx/spdx-3-model/blob/develop/docs/translation.md) - this includes the model decisions documented in the [2024-05-21 minutes](https://github.com/spdx/meetings/blob/main/tech/2024/2024-05-21.md) and [2024-06-06-translation minutes](https://github.com/spdx/meetings/blob/main/tech/2024/2024-06-06-translation.md)
- [Branch structure for the SPDX model repo](https://github.com/spdx/spdx-3-model/blob/develop/README.md#branch-structure) including documentation that translations should target the support branch

**Comment by goneall** [comment]
@kestewart @zvr @bact - let me know if you recall anything else we should capture here.

**Comment by bact** [comment]
@goneall thank you for the very detailed research! If there's anything that comes to my mind, I will post here.

**Comment by goneall** [comment]
from talking to @licquia we may be able to merge in PR #1141 without changing MKDocs or other changes then do the internationalization configuration after the merge - this way would have something to test with.

**Comment by bact** [comment]
Would be nice to have something to test with.

**Comment by zvr** [comment]
A number of comments on various bullet points. I'll number them so that any replies can refer to an index ;-)

1. Hard disagree on using multiple language codes on tags. This way madness lies. How would anyone know where to get a translation? We should have something with a single language code (e.g. `3.0.1-de`). When you get this tag, other languages may also be present (English will definitely be there, but you may also get Japanese). It doesn't matter; you got the official `de` translation.

1. I understand the reluctance of moving tags -- I am not a big fan myself. But how else would someone (automatically) get the "latest and greatest" version with whichever completed translations included? For example, the automation that publishes the website. Do we expect to manually keep updating the CI every time we add a new translation?

1. Do we agree that translations will never be moved to develop/main branches? It might be implied from our branching/tagging strategy, but we'd better write it down explicitly.

1. Minor point about translations, not documented anywhere: there will be a piece of data (e.g., lines in a file) that lists all languages included in the repo.

1. I understand that this is the spec repo, but do we want to include info on handling of translations in the model repo here? What about the using repo?

**Comment by goneall** [comment]
In response to @zvr comment above:

### 1. - language codes

@zvr are you OK tagging 3.0.1-L1, 3.0.1-L2, ...? This would solve the length issue of the tags.

### 2. - moving tags and publishing

We can get the latest tag in a give branch as described in [this StackOverflow article](https://stackoverflow.com/questions/77196619/how-to-get-a-tag-from-a-branch-in-my-repository-using-github-actions).  We would get the latest tag for each release branch and use that for the publication.

### 3. - translations moving to develop/main branch

I was making a different assumption - so definitely needs to be documented ;)  In thinking about it, we probably should do as suggested and not merge the translations to main or develop.  The process of updating the translations would be something like:

1. A new version of the spec is released in English only
2. Compare the new version main branch (or the new release support branch) with the previous release support branch to identify which files have been added or changed
3. For each translation, create a pull request against the support branch for the new version copying unchanged text and translating any new or modified text.

**Comment by NorioKobota** [comment]
Regarding the translation of the **spdx-spec** repo,
it is mentioned that 
_"We will structure the spec repo documentation as separate directories for different languages under the docs directory - see 2024-06-06-translation minutes and 2024-06-18 minutes."_ [here](https://github.com/spdx/spdx-spec/issues/1169#issue-2746385126).

However, as of now, a _[support/3.0 branch](https://github.com/spdx/spdx-spec/tree/support/3.0)_ has been created for spdx-spec repo, like the model repo, and the documents under the [docs folder](https://github.com/spdx/spdx-spec/tree/develop/docs) have not been moved to _'en'_ folder. 
Should we submit PRs to the support branch, same as the model repo? Or should we wait until the folder migration is completed?

Thanks!

**Comment by bact** [comment]
@NorioKobota We will try to figure out how to support new directory structure around the FOSDEM time (FOSDEM is 1-2 Feb and we plan to meet on 3 Feb hopefully). Will keep everybody updated.

**Comment by NorioKobota** [comment]
Sure. Thanks.
I’m really disappointed that I can’t attend FOSDEM and meet you.

**Comment by bact** [comment]
We eventually can't manage to meet and work in-person on this during FOSDEM.

Currently, I'm looking at how MkDocs can support multilingual website.

There will be two parts

1) Translation of the web UI
  - MkDocs natively supports this, see: https://www.mkdocs.org/dev-guide/translations/
2) Translation of the content
  - MkDocs supports this thru plugins.
  - For example, [mkdocs-static-i18n](https://ultrabug.github.io/mkdocs-static-i18n/) provides automatic language switching thru [a file extension/directory name convention](https://ultrabug.github.io/mkdocs-static-i18n/setup/choosing-the-structure/).

I will try to setup a demo to see if these cover our needs, how it works with our current tooling, and if there are any limitations.

**Comment by bact** [comment]
Update on mkdocs-static-i18n experiment; we can have something running but multiple versions of spec is not supported yet. 

- See #1191
