### ISSUE TITLE
Release SPDX 2.2

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-spec#163]
Tasks required to complete the release of the SPDX 2.2 specification:

- [x] All issues in the 2.2 milestone are closed or assigned to another milestone
- [x] All pull requests in the 2.2 milestone are closed or assigned to another milestone
- [x] Update 2.1 references in the specification (PR #178)
  - [x] Title
  - [x] 1.7 (Conformance)
  - [x] 2.1 (SPDX Version)
  - [x] 2.7 (License List Version)
  - [x] Appendix III
  - [x] Appendix V
- [x] Update list of contributors (PR #179)
- [x] Update copyright date (PR #177)
- [x] Add changelog entries to 1.9 (Differences from SPDX Specification 2.1) (PR #180)
- [x] Add changelog entries to `CHANGELOG.md `(PR #180)
- [x] Merge `development/v2.2` branch to `master`
- [x] Create `development/v2.2.1` branch and make it the default
- ~~[ ] Merge master to `development/v3.0`~~
- [x] Generate specification documents
  - [x] PDF
  - [x] HTML
  - [x] RDF
  - [x] OWL
- [x] Update RDF artifacts (PR #181)
  - [x] http://spdx.org/rdf/ontology/spdx-2-2
  - [x] chapters/img/spdx-2.2-rdf-ontology.png
- [x] Update https://spdx.org/specifications
  - [x] Update current version
  - [x] Add 2.1 to previous versions
  - [x] Update version on document structure image (also needs to be updated in `chapters/img/spdx-22.1-document.png`)
- [x] Update other website references to 2.2
  - [x] https://spdx.org/frequently-asked-questions-faq-0
  - [x] Add entry to ["Short History"](https://spdx.org/about)
- [x] Announcements
  - [x] Write up of blog
  - [x] Publish blog on LF site
  - [x] Publish reference to blog News on the [SPDX homepage](https://spdx.org/)
  - ~~[ ] Publish reference to blog on ACT~~
  - [x] Announcement email to main lists
  - [x] Announcement to OpenChain and any other relevant communities

**Comment by kestewart** [comment]
For discussion,   where should master go after 2.2 is released?   2.2.1 or 3.0

**Comment by swinslow** [comment]
Should we also add a checkbox in the list above to remove "DRAFT" where it appears in the spec, before the final publish+tag? I believe it is only in [1.8.2](https://github.com/spdx/spdx-spec/blob/development/v2.2/chapters/1-rationale.md#18-conformance-):

> 1.8.2 The official copyright notice to be used with any verbatim reproduction and/or distribution of this SPDX Specification 2.2-DRAFT is:

**Comment by kestewart** [comment]
@kestewart  to work on blog post for Thursday and set up meeting.

**Comment by kestewart** [comment]
Blog published at: https://www.linuxfoundation.org/blog/2020/05/spdx-2-2-specification-released/

**Comment by goneall** [comment]
Finally closing this issue - release was completed a while ago
