### ISSUE TITLE
Meta Issue - Update Schemas for 2.3

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#691]
This issue is to track the work needed to update all the schemas for SPDX release 2.3.

- [x] Resolve all SPDX issues and pull requests which impact the schemas (PR #671)
- [x] Diff the 2.2 and 2.3 versions of the spec to identify changes to the schemas
- [x] Update the OWL document based on the diff
- [x] Generate TTL version of OWL along with RDF (replaces PR #501 )
- [x] Generate JSON Schema
- [x] Review OWL and JSON schemas
- [x] Close issue #606
- [x] Close issue #459 
- [x] Close PR #547
- [x] Close PR #501

**Comment by goneall** [comment]
Note that the following 2.3 PR's and issues are assumed to only impact documentation and will not change impact the schema:
- PR #681 
- PR #679 
- PR #671 
- PR #464 
- Issue #657 
- Issue #630 
- Issue #593 
- Issue #587 
- Issue #582 
- Issue #571

**Comment by goneall** [comment]
> Gary, I've requested that the two pending items from PR 670 be addressed and resolved. See details of the two pending items in the meeting minutes

@rjb4standards Let me know kif this is resolved or something we should discuss on Tuesday's tech call

**Comment by goneall** [comment]
All tasks have been completed
