### ISSUE TITLE
Meta Issue - SPDX 2.3 release candidate

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#750]
Below are the remaining items which need to be completed before the review period can start for the SPDX 2.3 release:

- [x] Include the new How to Use Annex in the mkdocs generated html: @goneall 
- [x] Update all references to version 2.2 to version 2.3: @kestewart 
- [x] Update images ([spdx-spec](https://github.com/spdx/spdx-spec)/[chapters](https://github.com/spdx/spdx-spec/tree/development/v2.3/chapters)/img/ to refer to 2.3 and then update references to new images: @kestewart 
- [x] Add the new Ontology graphic and HTML: @zvr 
- [x] ~~Add annex for linking / external documents: @swinslow~~
- [x] Verify that the HTML is properly published to github.io: @tsteenbe @iamwillbar 
- [x] Update PR #761: @jlovejoy

**Comment by goneall** [comment]
> I think I still owe you a draft Annex for linking / external doc references. Going to try to get that together in the next few days if I can

Thanks @swinslow  I'll add it to the list.  

To avoid a conflict with PR #751 add it at the end as "Annex J".

**Comment by swinslow** [comment]
Discussed separately, I think the linking / external doc references document will be a page on the website whether than an Annex in the spec itself, so you can likely remove that task. Sorry for the confusion!

**Comment by goneall** [comment]
> https://github.com/spdx/spdx-spec/pull/761 is merged, so I think we can call that done?

@jlovejoy Yes - I closed this issue as complete.  Is there any other issues we should close?
